title: Hikaru Site
subtitle:
description:
author: Hikaru
email:
language: default

# Those makes up your site's full URL.
baseURL: https://yourdomain.com
rootDir: /

# Those paths exists on your disk.
srcDir: srcs
docDir: docs
themeDir: themes/aria

# Those paths are under `docDir`.
indexDir: .
archiveDir: archives
categoryDir: categories
tagDir: tags

# Those paths are under `srcDir`.
skipRender:
  - README.md

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

highlight:
  enable: true
  gutter: true
  hljs: true

search:
  enable: true
  path:
    - search/1.json
    # - search/2.json
    # - search/3.json
  page: search/index.html

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: false
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
