title: Hikaru Site
subtitle:
description:
author: Hikaru
email:
language: default

# Those makes up your site's full URL.
baseURL: https://yourdomain.com
rootDir: /

# Those paths are relative to your site dir.
srcDir: srcs
docDir: docs
themeDir: themes/aria

# Those paths are relative to `docDir`.
# Set to `null` if you don't want them.
indexDir: .
archiveDir: archives
categoryDir: categories
tagDir: tags

# Those paths are relative to `srcDir`.
skipRender:
  - README.md

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

nunjucks:
  autoescape: false

marked:
  gfm: true

highlight:
  enable: true
  gutter: true
  hljs: true

search:
  enable: true
  path:
    - search/1.json
    # - search/2.json
    # - search/3.json
  page: search/index.html

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: false
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
